import { Webpack } from "betterdiscord";
import { lazy } from "react";

export const [
    entireProfileModal,
    ModalAccessUtils,
    ModalRoot, 
    intl,
    ButtonClasses,
    ActivityActions,
    ActivityCardClasses,
    AnchorClasses,
    FetchApplications, 
    IconUtils, 
    Avatar,
    AvatarFetch, 
    EmojiRenderer, 
    MutualFriendRenderer, 
    MutualServerRenderer, 
    ActivityTimer, 
    MediaProgressBar, 
    ActivityButtons, 
    SpotifyButtons, 
    CallButtons,
    VoiceBox, 
    VoiceList, 
    VoiceIcon, 
    TagGuildRenderer, 
    RoleUpdater, 
    BotTagRenderer, 
    Tooltip,
    OrbTooltip,
    Popout, 
    FormSwitch,
    ProfileFetch,
    OpenSpotifyAlbumFromStatus,
    GameProfile,
    GameProfileCheck,
    DisplayNameStyleConfigurator,
    OpenUserSettings,
    PopUtils,
    RelationshipUtils,
    BlockToasts,
    Dispatcher,
    Endpoints,
    RestAPI,
    ProfileModalEntrypoint,
    ContentInventoryEntryByActivity,
    ClampedText,
    Clamp
] = /* @__PURE__ */ Webpack.getBulk(
    { filter: /* @__PURE__ */ Webpack.Filters.bySource('forceShowPremium', 'pendingThemeColors', 'profileThemeClassName') },
    { filter: x => x.openUserProfileModal },
    { filter: x=>x.Modal },
    { filter: x => x.t && x.t.formatToMarkdownString },
    { filter: x=> x.button && x.hasText && !x.hasTrailing },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('display', 'getUserOutbox') },
    { filter: /* @__PURE__ */ Webpack.Filters.byKeys('gameState', 'clickableImage') },
    { filter: /* @__PURE__ */ Webpack.Filters.byKeys('anchor', 'anchorUnderlineOnHover') },
    { filter: /* @__PURE__ */ Webpack.Filters.byKeys("fetchApplication") },
    { filter: /* @__PURE__ */ Webpack.Filters.byKeys("getGuildIconURL") },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('onOpenProfile', 'avatar') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('STREAMING', 'isVROnline') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('translateSurrogatesToInlineEmoji') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('MODAL_V2', 'discriminatorClass') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('hasAvatarForGuild', 'nick') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('timestamps', '.TEXT_FEEDBACK_POSITIVE'), searchExports: true },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('start', 'end', 'duration', 'percentage') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('activity', 'USER_PROFILE_ACTIVITY_BUTTONS') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('activity', 'PRESS_PLAY_ON_SPOTIFY_BUTTON') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('PRESS_JOIN_CALL_BUTTON') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('users', 'channel', 'themeType') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('maxUsers', 'guildId', 'getNickname') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('channel', 'isGuildStageVoice', 'isDM', '.CONNECT') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('guildId', 'name', 'setPopoutRef', 'onClose', 'fetchGuildProfile') },
    { filter: /* @__PURE__ */ x=>x.updateMemberRoles },
    { filter: /* @__PURE__ */ Webpack.Filters.bySource("BOT", "invertColor") },
    { filter: /* @__PURE__ */ Webpack.Filters.byPrototypeKeys(("renderTooltip")), searchExports: true  },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('showSubtext', 'caretConfig'), searchExports: true },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings("Unsupported animation config:"), searchExports: true },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('"data-toggleable-component":"switch"', 'layout:"horizontal"'), searchExports: true },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings("connectionsRoleId", "USER_PROFILE_FETCH_START"), searchExports: true },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings(".metadata)?void", ".EPISODE?"), searchExports: true },
    { filter: x => x.openGameProfileModal },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('gameProfileModalChecks',  'onOpened') },
    { filter: x => Webpack.Filters.byStrings('data-username-with-effects')(x?.type) },
    { filter: /* @__PURE__ */ Webpack.Filters.byKeys('openUserSettings') },
    { filter: /* @__PURE__ */ Webpack.Filters.byKeys('popAll') },
    { filter: x => x.unblockUser },
    { filter: x => x.showUnblockSuccessToast },
    { filter: x => x._dispatch, searchExports: true },
    { filter: /* @__PURE__ */ Webpack.Filters.byKeys("GUILD_EMOJI", "GUILD_EMOJIS"), searchExports: true },
    { filter: x => typeof x === "object" && x.del && x.put, searchExports: true },
    { filter: /* @__PURE__ */ Webpack.Filters.bySource('UserProfileModalV2', 'defaultWishlistId') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('getMatchingInboxEntry', 'getMatchingOutboxEntry') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('delay', 'lineClamp') },
    { filter: /* @__PURE__ */ Webpack.Filters.bySource('always-white', 'lineClamp', 'tabularNumbers') }
)

export const NavigationUtils = /* @__PURE__ */ Webpack.getMangled("transitionTo - Transitioning to", {
    transitionTo: /* @__PURE__ */ Webpack.Filters.byStrings("transitionTo - Transitioning to "),
    replace: /* @__PURE__ */ Webpack.Filters.byStrings("Replacing route with"),
    goBack: /* @__PURE__ */ Webpack.Filters.byStrings(".goBack()"),
    goForward: /* @__PURE__ */ Webpack.Filters.byStrings(".goForward()"),
    transitionToGuild: /* @__PURE__ */ Webpack.Filters.byStrings("transitionToGuild - Transitioning to")
});
export const ModalSystem = Webpack.getMangled(".modalKey?", {
    openModalLazy: Webpack.Filters.byStrings(".modalKey?"),
    openModal: Webpack.Filters.byStrings(",instant:"),
    closeModal: Webpack.Filters.byStrings(".onCloseCallback()"),
    closeAllModals: Webpack.Filters.byStrings(".getState();for")
});
export const MessageButtons = Webpack.getMangled('.zROXEV', {
    Button: Webpack.Filters.not(Webpack.Filters.byStrings("aria-label")),
    ButtonWithTooltip: Webpack.Filters.byStrings("tooltipText")
})
export const RoleRenderer = lazy(async () => ({ default: (await Webpack.waitForModule(Webpack.Filters.byStrings('roles', 'guild', 'canRemoveAnyRoles', 'map(e'), {searchExports: true} ))}));
