import { Webpack } from "betterdiscord";
import { lazy } from "react";

export const [
    entireProfileModal,
    ModalAccessUtils,
    ModalRoot, 
    intl,
    ButtonClasses,
    ActivityCardClasses,
    AnchorClasses,
    FetchGames,
    FetchApplications, 
    IconUtils, 
    AvatarFetch, 
    EmojiRenderer, 
    MutualFriendRenderer, 
    MutualServerRenderer, 
    ActivityTimer, 
    MediaProgressBar, 
    ActivityButtons, 
    SpotifyButtons, 
    CallButtons,
    VoiceBox, 
    VoiceList, 
    VoiceIcon, 
    TagGuildRenderer, 
    RoleRenderer,
    RolePermissionCheck,
    RoleUpdater, 
    BotTagRenderer, 
    Tooltip,
    OrbTooltip,
    Popout, 
    PopoutContainer,
    FormSwitch,
    ProfileFetch,
    OpenSpotifyAlbumFromStatus,
    GameProfile,
    DisplayNameStyleConfigurator,
    OpenUserSettings,
    PopUtils,
    RelationshipUtils,
    BlockToasts,
    Dispatcher,
    Endpoints,
    RestAPI
] = /* @__PURE__ */ Webpack.getBulk(
    { filter: /* @__PURE__ */ Webpack.Filters.bySource('forceShowPremium', 'pendingThemeColors', 'profileThemeClassName') },
    { filter: x => x.openUserProfileModal },
    { filter: x=>x.Modal },
    { filter: x => x.t && x.t.formatToMarkdownString },
    { filter: x=> x.button && x.hasText && !x.hasTrailing },
    { filter: /* @__PURE__ */ Webpack.Filters.byKeys('gameState', 'clickableImage') },
    { filter: /* @__PURE__ */ Webpack.Filters.byKeys('anchor', 'anchorUnderlineOnHover') },
    { filter: /* @__PURE__ */ Webpack.Filters.byKeys("getDetectableGamesSupplemental") },
    { filter: /* @__PURE__ */ Webpack.Filters.byKeys("fetchApplication") },
    { filter: /* @__PURE__ */ Webpack.Filters.byKeys("getGuildIconURL") },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('displayProfile', 'onOpenProfile', 'animateOnHover', 'previewStatus') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('translateSurrogatesToInlineEmoji') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('UserProfileMutualFriendRow') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('hasAvatarForGuild', 'nick') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('timestamps', '.TEXT_FEEDBACK_POSITIVE'), searchExports: true },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('start', 'end', 'duration', 'percentage') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('activity', 'USER_PROFILE_ACTIVITY_BUTTONS') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('activity', 'PRESS_PLAY_ON_SPOTIFY_BUTTON') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('PRESS_JOIN_CALL_BUTTON') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('users', 'channel', 'themeType') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('maxUsers', 'guildId') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('channel', 'isGuildStageVoice', 'isDM', '.CONNECT') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('guildId', 'name', 'setPopoutRef', 'onClose', 'fetchGuildProfile') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('roles', 'guild', 'canRemoveAnyRoles', 'map(e'), searchExports: true },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('.ADMINISTRATOR', '.MANAGE_MESSAGES') },
    { filter: /* @__PURE__ */ x=>x.updateMemberRoles },
    { filter: /* @__PURE__ */ Webpack.Filters.bySource("BOT", "invertColor") },
    { filter: /* @__PURE__ */ Webpack.Filters.byPrototypeKeys(("renderTooltip")), searchExports: true  },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('showSubtext', 'tooltipWordmarkComponent') },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings("Unsupported animation config:"), searchExports: true },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('type', 'position', 'data-popout-animating'), searchExports: true },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings('"data-toggleable-component":"switch"', 'layout:"horizontal"'), searchExports: true },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings("connectionsRoleId", "USER_PROFILE_FETCH_START"), searchExports: true },
    { filter: /* @__PURE__ */ Webpack.Filters.byStrings(".metadata)?void", ".EPISODE?"), searchExports: true },
    { filter: x => x.openGameProfileModal },
    { filter: x => Webpack.Filters.byStrings('data-username-with-effects')(x?.type) },
    { filter: /* @__PURE__ */ Webpack.Filters.byKeys('openUserSettings') },
    { filter: /* @__PURE__ */ Webpack.Filters.byKeys('popAll') },
    { filter: x => x.unblockUser },
    { filter: x => x.showUnblockSuccessToast },
    { filter: x => x._dispatch, searchExports: true },
    { filter: /* @__PURE__ */ Webpack.Filters.byKeys("GUILD_EMOJI", "GUILD_EMOJIS"), searchExports: true },
    { filter: x => typeof x === "object" && x.del && x.put, searchExports: true }
)

export const NavigationUtils = /* @__PURE__ */ Webpack.getMangled("transitionTo - Transitioning to", {
    transitionTo: /* @__PURE__ */ Webpack.Filters.byStrings("\"transitionTo - Transitioning to \""),
    replace: /* @__PURE__ */ Webpack.Filters.byStrings("\"Replacing route with \""),
    goBack: /* @__PURE__ */ Webpack.Filters.byStrings(".goBack()"),
    goForward: /* @__PURE__ */ Webpack.Filters.byStrings(".goForward()"),
    transitionToGuild: /* @__PURE__ */ Webpack.Filters.byStrings("\"transitionToGuild - Transitioning to \"")
});
export const ModalSystem = Webpack.getMangled(".modalKey?", {
    openModalLazy: Webpack.Filters.byStrings(".modalKey?"),
    openModal: Webpack.Filters.byStrings(",instant:"),
    closeModal: Webpack.Filters.byStrings(".onCloseCallback()"),
    closeAllModals: Webpack.Filters.byStrings(".getState();for")
});
export const TagRenderer = lazy(async () => ({ default: (await Webpack.waitForModule(Webpack.Filters.bySource('tag', 'isCurrentUser', 'widgetType', 'TAG_REMOVED'))).A}))